USE DBL
GO

-- 2. Procedimientos almacenados que permitan dar mantenimiento a la tabla CLIENTE.
IF OBJECT_ID('SP_NUEVOCLIENTE') IS NOT NULL
    DROP PROCEDURE SP_NUEVOCLIENTE
GO

CREATE PROCEDURE SP_NUEVOCLIENTE(
    @COD CHAR(5),
    @APE VARCHAR(30),
    @NOM VARCHAR(30),
    @DNI CHAR(8),
    @TEL VARCHAR(25),
    @DIS CHAR(3),
    @COR VARCHAR(50)
)
AS
BEGIN
    INSERT INTO CLIENTE VALUES (@COD, @APE, @NOM, @DNI, @TEL, @DIS, @COR)
END
GO

IF OBJECT_ID('SP_MODIFICACLIENTE') IS NOT NULL
    DROP PROCEDURE SP_MODIFICACLIENTE
GO

CREATE PROCEDURE SP_MODIFICACLIENTE(
    @COD CHAR(5),
    @APE VARCHAR(30),
    @NOM VARCHAR(30),
    @DNI CHAR(8),
    @TEL VARCHAR(25),
    @DIS CHAR(3),
    @COR VARCHAR(50)
)
AS
BEGIN
    UPDATE CLIENTE
    SET APE_CLI = @APE, NOM_CLI = @NOM,
        DNI_CLI = @DNI, TEL_CLI = @TEL,
        IDE_DIS = @DIS, COR_CLI = @COR
    WHERE IDE_CLI = @COD
END
GO

IF OBJECT_ID('SP_ELIMINACLIENTE') IS NOT NULL
    DROP PROCEDURE SP_ELIMINACLIENTE
GO

CREATE PROCEDURE SP_ELIMINACLIENTE(
    @COD CHAR(5)
)
AS
BEGIN
    DELETE FROM CLIENTE
    WHERE IDE_CLI = @COD
END
GO

-- PRUEBA
EXEC SP_NUEVOCLIENTE 'CL009', 'ROLF', 'CARLOS', '45784598', '541-5858', 'L05', 'CROLF@GMAIL.COM'
GO

EXEC SP_MODIFICACLIENTE 'CL009', 'ROLF', 'CARLOS', '45784598', '541-5858', 'L05', 'CROLF@GMAIL.COM'
GO

EXEC SP_ELIMINACLIENTE 'CL009'
GO