USE DBL
GO

-- 3. Procedimiento almacenado que determine el último código del cliente registrado.
IF OBJECT_ID('SP_ULTIMOCODIGO') IS NOT NULL
    DROP PROCEDURE SP_ULTIMOCODIGO
GO

CREATE PROCEDURE SP_ULTIMOCODIGO
AS
BEGIN
    SELECT TOP 1 C.IDE_CLI
    FROM CLIENTE C
    ORDER BY C.IDE_CLI DESC
END
GO

-- PRUEBA
EXEC SP_ULTIMOCODIGO
GO