USE DBL
GO

-- 5. Procedimiento almacenado que permita listar los clientes de un determinado distrito.
IF OBJECT_ID('SP_CLIENTESxDISTRITO') IS NOT NULL
    DROP PROCEDURE SP_CLIENTESxDISTRITO
GO

CREATE PROCEDURE SP_CLIENTESxDISTRITO(
    @DISTRITO VARCHAR(30)
)
AS
BEGIN
    SELECT C.IDE_CLI AS CODIGO, 
           C.APE_CLI AS APELLIDOS,
           C.NOM_CLI AS NOMBRES, 
           C.DNI_CLI AS DNI,
           C.TEL_CLI AS TELEFONO,
           D.DES_DIS AS DISTRITO,
           C.COR_CLI AS CORREO
    FROM CLIENTE C
    JOIN DISTRITO D ON C.IDE_DIS = D.IDE_DIS
    WHERE D.DES_DIS = @DISTRITO
END
GO

-- PRUEBA
EXEC SP_CLIENTESxDISTRITO 'LOS OLIVOS'
GO
