USE DBL
GO
-- 8. Procedimiento almacenado que muestra el detalle de alquiler de acuerdo al nombre de un determinado cliente.
IF OBJECT_ID('SP_DETALLExCLIENTE') IS NOT NULL
    DROP PROCEDURE SP_DETALLExCLIENTE
GO

CREATE PROCEDURE SP_DETALLExCLIENTE(
    @CLIENTE VARCHAR(30)
)
AS
BEGIN
    SELECT D.NUM_ALQ AS ALQUILER,
           C.NOM_CLI + SPACE(1) + C.APE_CLI AS CLIENTE,
           D.MAT_AUT AS MATRICULA
    FROM CLIENTE C
    JOIN DETALLEALQUILER D ON C.IDE_CLI = D.IDE_CLI
    WHERE C.NOM_CLI + SPACE(1) + C.APE_CLI = @CLIENTE
END
GO

-- PRUEBA
EXEC SP_DETALLExCLIENTE 'MANUEL CARLOS'
GO