-- ******************** Scripts Sesión 02 ******************** 
-- TEMA: Fomrato de variables
-- ** 1ra version
DECLARE @MONTO MONEY
SET @MONTO= 1250.75
PRINT 'EL MONTO INGRESADO ES: '+@MONTO
GO

DECLARE @MONTO MONEY
SET @MONTO= 1250.75
PRINT 'EL MONTO INGRESADO ES: '+LTRIM(STR(@MONTO))
GO

-- ** 2da version
DECLARE @MONTO MONEY
SET @MONTO= 1250.75
SELECT @MONTO AS [VALOR DE MONTO]
GO

-- ** 3ra version
DECLARE @MONTO MONEY
SET @MONTO= 1250.75
PRINT 'EL MONTO INGRESADO ES: '+CAST(@MONTO AS VARCHAR(10))
GO

DECLARE @MONTO MONEY
SET @MONTO= 1250.75
PRINT 'EL MONTO INGRESADO ES: '+CONVERT(CHAR(7),@MONTO)
GO

DECLARE @MONTO MONEY
SET @MONTO= 1250.75
SELECT @MONTO AS 'MONTO INGRESADO'
GO
-- ** Cuarta versión:
DECLARE @MONTO MONEY
SET @MONTO= 1250.75
PRINT 'EL MONTO INGRESADO ES: '+CONVERT(VARCHAR(10),@MONTO)
GO